{
 "title": "AMD GPU Metrics",
 "description": "AMD GPU Metrics based on the prometheus metrics from github.com/utkuozdemir/nvidia_gpu_exporter",
 "tags": [
  "amd",
  "rocm-smi",
  "amd_gpu_exporter",
  "prometheus"
 ],
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "5s",
 "templating": {
  "list": [
   {
    "name": "gpu",
    "label": "GPU",
    "query": {
     "query": "label_values(rocm_smi_index, uuid)"
    }
   }
  ]
 },
 "panels": [
  {
   "title": "Name",
   "type": "stat",
   "description": "The official product name of the GPU. This is an alphanumeric string. For all products.",
   "gridPos": { "h": 3, "w": 4, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rocm_smi_gpu_name{uuid=\"$gpu\"}",
     "legendFormat": "{{gpu_name}}"
    }
   ]
  },
  {
   "title": "P-State",
   "type": "stat",
   "description": "The current performance state for the GPU. States range from auto, low, high or manual.",
   "gridPos": { "h": 3, "w": 2, "x": 4, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "prefix:P" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rocm_smi_p_state{uuid=\"$gpu\"}",
     "legendFormat": "{{label_name}}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "gauge",
   "description": "Core GPU temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rocm_smi_temperature_gpu{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Fan Speed %",
   "type": "gauge",
   "description": "The fan speed value is the percent of the product's maximum noise tolerance fan speed that the device's fan is currently intended to run at. This value may exceed 100% in certain cases. Note: The reported speed is the intended fan speed. If the fan is physically blocked and unable to spin, this output will not match the actual fan speed. Many parts do not report fan speeds because they rely on cooling via fans in the surrounding enclosure.\n",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rocm_smi_fan_speed{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "Video Clock Speed",
   "type": "timeseries",
   "description": "Current frequency of video encoder/decoder clock.",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "rocm_smi_clocks_current_graphics_clock_hz{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Memory Utilization %",
   "type": "timeseries",
   "description": "Percent of time over the past sample period during which global (device) memory was being read or written.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rocm_smi_utilization_memory_ratio{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Driver Version",
   "type": "stat",
   "description": "The version of the installed AMD display driver. This is an alphanumeric string.",
   "gridPos": { "h": 2, "w": 3, "x": 0, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rocm_smi_driver_version{uuid=\"$gpu\"}",
     "legendFormat": "{{driver_version}}"
    }
   ]
  },
  {
   "title": "Vbios Version",
   "type": "stat",
   "description": "The BIOS of the GPU board.",
   "gridPos": { "h": 2, "w": 3, "x": 3, "y": 3 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rocm_smi_vbios_version{uuid=\"$gpu\"}",
     "legendFormat": "{{vbios_version}}"
    }
   ]
  },
  {
   "title": "Memory Allocation",
   "type": "timeseries",
   "description": "Total memory allocated by active contexts.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "decbytes" } },
   "targets": [
    {
     "expr": "rocm_smi_memory_used_bytes{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "GPU Utilization %",
   "type": "gauge",
   "description": "Percent of time over the past sample period during which one or more kernels was executing on the GPU.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rocm_smi_utilization_gpu_ratio{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Power Draw %",
   "type": "gauge",
   "description": "The last measured power draw for the entire board, in watts. Only available if power management is supported. This reading is accurate to within +/- 5 watts / The software power limit in watts.",
   "gridPos": { "h": 5, "w": 3, "x": 9, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rocm_smi_power_draw_watts{uuid=\"$gpu\"} / rocm_smi_power_default_limit_watts{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "Power Draw",
   "type": "timeseries",
   "description": "The last measured power draw for the entire board, in watts. Only available if power management is supported. This reading is accurate to within +/- 5 watts",
   "gridPos": { "h": 5, "w": 6, "x": 12, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "watt" } },
   "targets": [
    {
     "expr": "rocm_smi_power_draw_watts{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "GPU Utilization %",
   "type": "timeseries",
   "description": "Percent of time over the past sample period during which one or more kernels was executing on the GPU.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rocm_smi_utilization_gpu_ratio{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "Memory Clock Speed",
   "type": "timeseries",
   "description": "Current frequency of memory clock.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "rocm_smi_clocks_current_memory_clock_hz{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Memory Allocation %",
   "type": "gauge",
   "description": "Total memory allocated by active contexts / Total installed GPU memory.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rocm_smi_memory_used_bytes{uuid=\"$gpu\"} / rocm_smi_memory_total_bytes{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "Fan Speed %",
   "type": "timeseries",
   "description": "The fan speed value is the percent of the product's maximum noise tolerance fan speed that the device's fan is currently intended to run at. This value may exceed 100% in certain cases. Note: The reported speed is the intended fan speed. If the fan is physically blocked and unable to spin, this output will not match the actual fan speed. Many parts do not report fan speeds because they rely on cooling via fans in the surrounding enclosure.\n",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "targets": [
    {
     "expr": "rocm_smi_fan_speed{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Graphics Clock Speed",
   "type": "timeseries",
   "description": "Current frequency of graphics (shader) clock.",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "hertz" } },
   "targets": [
    {
     "expr": "rocm_smi_clocks_current_graphics_clock_hz{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  },
  {
   "title": "Memory Utilization %",
   "type": "gauge",
   "description": "Percent of time over the past sample period during which global (device) memory was being read or written.\nThe sample period may be between 1 second and 1/6 second depending on the product.",
   "gridPos": { "h": 5, "w": 3, "x": 6, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "last" ] } },
   "targets": [
    {
     "expr": "rocm_smi_utilization_memory_ratio{uuid=\"$gpu\"}"
    }
   ]
  },
  {
   "title": "Temperature",
   "type": "timeseries",
   "description": "Core GPU temperature. in degrees C.",
   "gridPos": { "h": 5, "w": 6, "x": 18, "y": 15 },
   "fieldConfig": { "defaults": { "unit": "celsius" } },
   "targets": [
    {
     "expr": "rocm_smi_temperature_gpu{uuid=\"$gpu\"}",
     "legendFormat": "{{uuid}}"
    }
   ]
  }
 ]
}